### ISSUE TITLE
CSS and JavaScript got injected two times in every file

### ISSUE THREAD

**Issue by Weber-D** [ibmcnxdev/customizer#21]
Using the [hello world example](https://github.com/ibmcnxdev/customizer/tree/master/samples/helloWorld) I noticed that the content of each file is served two times. Doesn't seem to make any difference if we have js or css files. 

Simple example: I create a file called `style.css` with the following content: 

```
.lotusHeader .shareSome-desc .shareSome-title{
    font-size:40px;
    color:orange
}
```

When I access the injected file from the webserver, It has the following content: 

```
.lotusHeader .shareSome-desc .shareSome-title{
    font-size:40px;
    color:orange
}
```

That's not only a performance issue case it also applys to javascript, so that every code got executet two times.

**Comment by briangleeson** [comment]
Not sure I follow, your style.css content is the same as the content you posted from injected file from webserver. 

Did you see each file injected twice in the returned HTML? Or two requests fetching each file? What env were you using?

Any more detail you can provide would be useful

**Comment by Weber-D** [comment]
The file itself (`main.css`) is only referenced once in the html page source: 

    <link rel='stylesheet' type='text/css' href='/files/customizer/my-theme/dist/main.css?cache-control=max-age%3D0'>

But `style.css` contains it's content two times in a row like this (updated the post, too)

```css
.lotusHeader .shareSome-desc .shareSome-title{
    font-size:40px;
    color:orange
}
.lotusHeader .shareSome-desc .shareSome-title{
    font-size:40px;
    color:orange
}
```
This seems to be a bug somewhere in the customization-system, since the file uploaded by me is fine (no redundant content). 

To be more clear, I have the `main.css` file with the following content: 

```css
.lotusHeader .shareSome-desc .shareSome-title{
    font-size:40px;
    color:orange
}
```
It got uploaded in `customizer/my-theme/dist/main.css` on the server. Now I access the file using our webserver on http://my-host/files/customizer/my-theme/dist/main.css and got this: 

```css
.lotusHeader .shareSome-desc .shareSome-title{
    font-size:40px;
    color:orange
}
.lotusHeader .shareSome-desc .shareSome-title{
    font-size:40px;
    color:orange
}
```

We're having a pink testsystem with kubernetes. I'm mainly a C# developer and completely new on any IBM software, just got recently started on the pink stack. The connection about page say `Release v6.0.0.0 Build IC6.0_CR_Integration_20171116-0701`. Is this enough or do you need further information?
